[build-system]
requires = ["setuptools>=42.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.versioneer]
VCS = "git"
style = "pep440"
versionfile_source = "iplotLogging/_version.py"
versionfile_build = "iplotLogging/_version.py"
tag_prefix = ""
parentdir_prefix = ""


